### PR TITLE
Use core Nav logic in MobileNav.

### PR DESCRIPTION
**Pull request by lindapaiste**
The main purpose of reusing the existing components is to get the logic for focus/blur/etc. without having to rewrite anything.

- Clicking an icon a second time closes the menu.
- Clicking the logo opens or closes the more menu.  (Now I'm realizing that I didn't check it on the my stuff pages.  Wonder if that messes anything up.)
- I added a `toggleDropdownOpen` function to the `NavBarContext` in order to do this.
- I moved the `Logo` to a separate component because the `useContext(NavBarContext)` cannot be called in the `MobileNav`. It has to be inside the context provider which is the `Nav`.
- You can navigate through menu items with the Tab key but it's not exactly how I wanted it.  Pressing Tab when focused on the account icon opens that menu and you have to go through its items to get over to the more menu.  I want it so that you have to press Enter to go into a menu, and the Tab should go from the account icon to the more icon.
- I made the `NavBar` take the `className` as a prop so that we can style it.  We could have it apply the `nav` class alongside the added `className` but right now it overrides it.
- The existing `NavDropdownMenu` component has too much UI in it and I just want the logic, so I moved the parts that I want to reuse into a `useMenuProps` hook and exported that.
- After my changes the `nav__dropdown-item` class is getting applied to the menu items, which doesn't seem to cause any problems as its a pretty basic style.  You could probably remove some of the styles in your `Options` which duplicate this.
- Instead of putting a `button` inside of an `a` we're using either one and styling them the same.  I did that by changing your `button` style to `a, button`.
- I'm adding an `opened` class to the `ul` to control the style instead of using focus.  I got rid of the `focus` selectors (instead of keeping both) because I thought that clicking the icon again should close the menu.

### CODE REVIEW

**Comment by dewanshDT** [comment]
The only change I have in mind is, we don't want the astrisk Logo to open the more menu. I was previously required in the older designs that it should open the account menu but we discussed this before and decided that It should not open more or the account menu, and add a separate icon for the account menu

**Comment by dewanshDT** [comment]
and the tests are failing

**Comment by lindapaiste** [comment]
> The only change I have in mind is, we don't want the astrisk Logo to open the more menu. I was previously required in the older designs that it should open the account menu but we discussed this before and decided that It should not open more or the account menu, and add a separate icon for the account menu

Ah ok I forgot that's what we decided.  I know at some point we discussed the possibility that both the logo and another icon would both open the menu.

**Comment by dewanshDT** [comment]
okayy, should I merge this? how can we fix the tests though

**Comment by dewanshDT** [comment]
okay, this is good to go!

**Comment by lindapaiste** [comment]
Yes merge it.  I fixed the tests by using a `react-responsive` context provider like we discussed.

It seems like we need to regenerate the snapshots every type we update a `styled-components` style because it gets a different generated class name, so that's annoying.

I also had to mock the project name that's used for the initial state of the redux store.  Otherwise every time we run the tests we'll get a different random name.

**Pull request merged**
